prototype/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views

from . import views

urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("ticket/<int:ticket_id>/", views.ticket, name="ticket"),
    path("ticket/create/", views.create_ticket, name="create_ticket"),
    path("ticket/edit/<int:ticket_id>/", views.edit_ticket, name="edit_ticket"),
    path("ticket/<int:ticket_id>/add_comment", views.add_comment, name="add_comment"),
    path("register/", views.register, name="register"),
    path("accounts/", include("django.contrib.auth.urls"))
]

prototype_proj/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("prototype.urls")),
    path('admin/', admin.site.urls),
]

prototype/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from encrypted_fields import fields

User._meta.get_field("email")._unique = True
User._meta.get_field("email").blank = False
User._meta.get_field("email").null = False
User._meta.get_field("first_name").blank = False
User._meta.get_field("first_name").null = False
User._meta.get_field("last_name").blank = False
User._meta.get_field("last_name").null = False


class Company(models.Model):
    name = models.CharField(max_length=256)
    domain = models.CharField(max_length=100, blank=True)

    def __str__(self):
        return self.name


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name="profile")
    company = models.ForeignKey(Company, on_delete=models.CASCADE, null=True)
    ROLE_CHOICES = [("STAFF", "Staff"), ("CLIENT", "Client")]
    role = models.CharField(choices=ROLE_CHOICES, default="CLIENT", max_length=10)

    def is_client(self):
        return self.role == "CLIENT"


@receiver(post_save, sender=User)
def update_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)
    instance.profile.save()


class Ticket(models.Model):
    PRIORITY_CHOICES = [(1, "High"), (2, "Medium"), (3, "Low")]
    TYPE_CHOICES = [("DEV", "Development"), ("TEST", "Testing"), ("PROD", "Production")]
    STATUS_CHOICES = [("OPEN", "Open"), ("RES", "Resolved"), ("CLOSED", "Closed")]

    description = fields.EncryptedTextField(default="")
    steps = fields.EncryptedTextField(default="")
    created_datetime = models.DateField(auto_now=True)
    type = models.CharField(choices=TYPE_CHOICES, default="DEV", max_length=20)
    status = models.CharField(choices=STATUS_CHOICES, default="OPEN", max_length=15)
    priority = models.IntegerField(choices=PRIORITY_CHOICES, default=1)

    company = models.ForeignKey(Company, on_delete=models.CASCADE)
    author = models.ForeignKey(
        User, on_delete=models.SET_NULL, related_name="created_tickets", null=True
    )
    assignee = models.ForeignKey(
        User, on_delete=models.SET_NULL, related_name="assigned_tickets", null=True
    )

    def __str__(self):
        return f"Ticket {str(self.id)}"


class TicketComment(models.Model):
    description = fields.EncryptedTextField()
    created_at = models.DateField(auto_now=True)

    ticket = models.ForeignKey(
        Ticket, on_delete=models.CASCADE, related_name="comments"
    )
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return self.description

prototype/forms.py
from crispy_forms.helper import FormHelper
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.core.exceptions import ObjectDoesNotExist

from .models import Company, Ticket, TicketComment


class CreateTicketFormClient(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(CreateTicketFormClient, self).__init__(*args, **kwargs)
        self.helper = FormHelper

    class Meta:
        model = Ticket
        fields = ["steps", "description", "type", "priority"]

    def is_client_form(self):
        return True


class CreateTicketForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(CreateTicketForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper

    class Meta:
        model = Ticket
        fields = ["steps", "description", "type", "priority", "company", "assignee"]

    def is_client_form(self):
        return False


class CreateTicketFormFactory:
    def __init__(self, profile):
        self.profile = profile

    def generate_form(self, *args):
        if self.profile.is_client():
            return CreateTicketFormClient(*args)
        else:
            return CreateTicketForm(*args)


class EditTicketForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(EditTicketForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper

    class Meta:
        model = Ticket
        fields = [
            "steps",
            "description",
            "status",
            "type",
            "priority",
            "company",
            "assignee",
        ]

    def clean(self):
        super(EditTicketForm, self).clean()

        cd = self.cleaned_data
        if self.instance.status == "OPEN" and cd.get("status") == "CLOSED":
            self.add_error(
                "status",
                "This status cannot be set yet. Please set to Resolved before Closed",
            )
        return cd


class AddCommentForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(AddCommentForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper

    class Meta:
        model = TicketComment
        fields = ["description"]


class RegisterForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super(RegisterForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper

    class Meta:
        model = User
        fields = [
            "username",
            "first_name",
            "last_name",
            "email",
            "password1",
            "password2",
        ]

    def clean(self):
        super(RegisterForm, self).clean()
        cd = self.cleaned_data
        domain = cd.get("email").split("@")[1]
        try:
            Company.objects.get(domain=domain)
        except ObjectDoesNotExist:
            self.add_error(
                "email",
                "This email domain is not registered to any company in our database.",
            )
        return cd

prototype/views.py
from django.shortcuts import render, get_object_or_404
from django.http import Http404, HttpResponse, HttpResponseForbidden
from django.views import generic
from django.urls import reverse
from django.shortcuts import redirect
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import login, authenticate
from django.contrib.auth.decorators import login_required
from django.core.exceptions import ObjectDoesNotExist

from .models import Ticket, Company, TicketComment
from .forms import AddCommentForm, CreateTicketFormFactory, RegisterForm, EditTicketForm

# Create your views here.
class IndexView(LoginRequiredMixin, generic.ListView):
    template_name = "prototype/index.html"
    context_object_name = "tickets"

    def get_queryset(self):
        user = self.request.user
        if user.profile.role == "CLIENT":
            return Ticket.objects.filter(
                company=self.request.user.profile.company
            ).order_by("-created_datetime")
        return Ticket.objects.order_by("-created_datetime")


def access_allowed(request, ticket):
    if (
        request.user.profile.is_client()
        and ticket.company != request.user.profile.company
    ):
        return False
    else:
        return True


@login_required
def ticket(request, ticket_id):
    ticket = get_object_or_404(Ticket, pk=ticket_id)

    if not access_allowed(request, ticket):
        return HttpResponseForbidden()

    comments = TicketComment.objects.filter(ticket_id=ticket_id)
    return render(
        request,
        template_name="prototype/ticket_detail.html",
        context={"ticket": ticket, "comments": comments},
    )


@login_required
def create_ticket(request):
    factory = CreateTicketFormFactory(request.user.profile)
    if request.method == "POST":
        form = factory.generate_form(request.POST)
        if form.is_valid():
            new_ticket = form.save(commit=False)
            cd = form.cleaned_data
            print(cd)
            if request.user.profile.is_client():
                new_ticket.company = request.user.profile.company
            else:
                new_ticket.company = cd.get("company")
                new_ticket.assignee = cd.get("assignee")
            new_ticket.author = request.user
            new_ticket.save()
            return redirect("/")
    else:
        form = factory.generate_form()
    return render(request, "prototype/create_ticket.html", context={"form": form})


@login_required
def edit_ticket(request, ticket_id):
    ticket = get_object_or_404(Ticket, pk=ticket_id)

    if not access_allowed(request, ticket) or request.user.profile.is_client():
        return HttpResponseForbidden()

    form = EditTicketForm(request.POST or None, instance=ticket)
    if request.method == "POST" and form.is_valid():
        form.save()
        return redirect("/")
    return render(request, "prototype/edit_ticket.html", context={"form": form})


@login_required
def add_comment(request, ticket_id):
    ticket = get_object_or_404(Ticket, pk=ticket_id)

    if not access_allowed(request, ticket):
        return HttpResponseForbidden()

    if request.method == "POST":
        form = AddCommentForm(request.POST)
        if form.is_valid():
            print("FORM VALID")
            new_comment = form.save(commit=False)
            new_comment.ticket = ticket
            new_comment.author = request.user
            new_comment.save()
            return redirect("ticket", ticket_id=ticket_id)
    else:
        form = AddCommentForm()
    return render(request, "prototype/add_comment.html", context={"form": form})


def register(request):
    if request.method == "POST":
        form = RegisterForm(request.POST)
        if form.is_valid():
            email_domain = form.cleaned_data.get("email").split("@")[1]
            company = Company.objects.get(domain=email_domain)
            user = form.save()
            user.refresh_from_db()
            user.profile.company_id = company.id
            user.profile.save()
            if user.profile.company.name == "Safari Security":
                user.profile.role = "STAFF"
            user.save()
            password = form.cleaned_data.get("password1")
            user = authenticate(username=user.username, password=password)
            login(request, user)
            return redirect("/")
    else:
        form = RegisterForm()
    return render(request, "registration/register.html", context={"form": form})

prototype/templates/prototype/add_comment.html
{% extends "layout.html" %}

{% block app_content %}
{% load crispy_forms_tags %}
<form method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <input class="btn btn-primary" type="submit" value="Submit"/>
</form>
{% endblock %}

prototype/templates/prototype/create_ticket.html
{% extends "layout.html" %}

{% block app_content %}
{% load crispy_forms_tags %}
<form method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <input class="btn btn-primary" type="submit" value="Submit"/>
</form>
{% endblock %}

prototype/templates/prototype/default_form.html
{% extends "layout.html" %}

{% block app_content %}
{% load crispy_forms_tags %}
<form method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <input class="btn btn-primary" type="submit" value="Edit"/>
</form>
{% endblock %}

prototype/templates/prototype/edit_ticket.html
{% extends "layout.html" %}

{% block app_content %}
{% load crispy_forms_tags %}
<form method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <input class="btn btn-primary" type="submit" value="Submit"/>
</form>
{% endblock %}

prototype/templates/prototype/index.html
{% extends "layout.html" %}

{% block app_content %}
{% if tickets %}
    <h2>Tickets</h2>
    <table class="mdl-data-table mdl-js-data-table">
        <thead>
            <tr>
                <th>ID</th>
                <th class="mdl-data-table__cell--non-numeric">Status</th>
                <th class="mdl-data-table__cell--non-numeric">Priority</th>
                <th class="mdl-data-table__cell--non-numeric">Description</th>
                <th class="mdl-data-table__cell--non-numeric">Type</th>
                <th class="mdl-data-table__cell--non-numeric">Company</th>
                <th class="mdl-data-table__cell--non-numeric">Assigned To</th>
                <th>Date Created</th>
                <th class="mdl-data-table__cell--non-numeric">View</th>
                {% if not user.profile.is_client %}
                <th class="mdl-data-table__cell--non-numeric">Edit</th>
                {% endif %}
            </tr>
        </thead>
        <tbody>
            {% for ticket in tickets %}
            <tr>
                <td>{{ ticket.id }}</td>
                <td>{{ ticket.get_status_display }}</td>
                <td>{{ ticket.get_priority_display }}</td>
                <td>{{ ticket.description }}</td>
                <td>{{ ticket.get_type_display }}</td>
                <td>{{ ticket.company }}</td>
                <td>{{ ticket.assigned_to }}</td>
                <td>{{ ticket.created_datetime }}</td>
                <td><a class="mdl-button mdl-js-button mdl-button--icon" href="{% url "ticket" ticket.id %}"><i class="material-icons" >visibility</i></a></td>
                {% if not user.profile.is_client %}
                <td><a class="mdl-button mdl-js-button mdl-button--icon mdl-button--colored" href="{% url "edit_ticket" ticket.id %}"><i class="material-icons" >create</i></a></td>
                {% endif %}
            </tr>
            {% endfor %}
        </tbody>
    </table>
    </ul>
{% else %}
    <p>No tickets available.</p>
{% endif %}
{% endblock %}

prototype/templates/prototype/ticket_detail.html
{% extends "layout.html" %}

{% block app_content %}
{% if ticket %}
<h2>Ticket Details</h2>
{% if not user.is_client %}
<a class="btn btn-primary" href="{% url "edit_ticket" ticket.id %}" role="button">Edit Ticket</a>
{% endif %}
<div class="mdl-grid">
    <div class="mdl-cell mdl-cell--4-col">
        <table class="mdl-data-table mdl-js-data-table">
            <tr>
                <th>
                    ID:
                </th>
                <td>
                    {{ ticket.id }}
                </td>
            </tr>
            <tr>
                <th>
                    Created on:
                </th>
                <td>
                    {{ ticket.created_datetime }}
                </td>
            </tr>
            <tr>
                <th class="mdl-data-table__cel--non-numeric">
                    Type:
                </th>
                <td>
                    {{ ticket.get_type_display }}
                </td>
            </tr>
            <tr>
                <th class="mdl-data-table__cel--non-numeric">
                    Status:
                </th>
                <td>
                    {{ ticket.get_status_display }}
                </td>
            </tr>
            <tr>
                <th>
                    Priority:
                </th>
                <td>
                    {{ ticket.get_priority_display }}
                </td>
            </tr>
            <tr>
                <th>
                    Company:
                </th>
                <td>
                    {{ ticket.company.name }}
                </td>
            </tr>
            <tr>
                <th>
                    Author:
                </th>
                <td>
                    {% if ticket.author %}
                    {{ ticket.author.first_name }} {{ ticket.author.last_name }}
                    {% else %}
                    No author registered.
                    {% endif %}
                </td>
            </tr>
        </table>
    </div>
    <div class="mdl-cell mdl-cell--4-col">
        <table class="mdl-data-table mdl-js-data-table">
            <tr>
                <th class="mdl-data-table__cell--non-numeric">
                    Steps to reproduce:
                </th>
                <td>
                    {{ ticket.steps|linebreaks }}
                </td>
            </tr>
            <tr>
                <th class="mdl-data-table__cell--non-numeric">
                    Description:
                </th>
                <td>
                    {{ ticket.description|linebreaks }}
                </td>
            </tr>
        </table>
    </div>
</div>
<div class="mdl-grid">
    <div class="mdl-cell mdl-cell--8-col">
    <h3>Comments</h3>
        {% if ticket.status != "CLOSED" %}
        <a class="btn btn-primary" role="button" href="{% url "add_comment" ticket.id %}">Add Comment</a>
        {% endif %}
        {% if comments|length == 0 %}
        <p> This ticket doesnt have any comments.</p>
        {% else %}
        <table class="mdl-data-table mdl-js-data-table">
            {% for comment in comments %}
            <tr>
                <th class="mdl-data-table__cell--non-numeric">
                    {{ comment.author }} on {{ comment.created_at }}
                </th>
                <td>
                <div style="width: 80em; word-wrap: break-word; white-space: normal;">
                    {{ comment.description }}
                </div>
                </td>
            </tr>
            {% endfor %}
        </table>
        {% endif %}
    </div>
</div>
{% else %}
<p class="display-2">Invalid ticket ID.</p>
{% endif %}
{% endblock app_content %}